path: C:/Users/hiyos/OneDrive - 埼玉大学/あかとき/プログラム/SC-25/yolo_class1/dataset  # dataset root directory
train: images/train  # training images (relative to 'path')
val: images/val  # validation images (relative to 'path')
test: images/test # optional test images

nc:
  1  # number of classes
names:
  0: colorcoon
